[build-system]
requires = ["setuptools>=62.3"]
build-backend = "setuptools.build_meta"

[project]
name = "mpo_yampfs"
version = "0.2.1"
authors = [
    {name = "hyperbola0"},
]
description = "An open source randomizer patcher for Metroid Prime Origins."
readme = "README.md"
license = {file = "LICENSE.txt"}
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.11"

]
dependencies = [
    "pythonnet",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
]


[project.urls]
Repository = "https://github.com/steven11sjf/yampfs"


# Entry Points for PyInstaller
[project.entry-points.pyinstaller40]
hook-dirs = "mpo_yampfs.__pyinstaller:get_hook_dirs"


[tool.setuptools]
packages = ["mpo_yampfs", "mpo_yampfs.__pyinstaller"]

[tool.setuptools.package-data]
"*" = ["yampfs/**"]
"yampfs_py.yampfs" = ["**"]


[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "mpo_yampfs_tests",
]