[build-system]
requires = ["setuptools>=62.3"]
build-backend = "setuptools.build_meta"

[project]
name = "mpo_yampfs"
version = "0.2.7"
authors = [
    {name = "hyperbola0"},
]
description = "An open source randomizer patcher for Metroid Prime Origins."
readme = "README.md"
license = "GPL-3.0-or-later"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3.12"
]

dependencies = [
    "pythonnet",
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "pytest-mock",
]


[project.urls]
Repository = "https://github.com/steven11sjf/yampfs"


# Entry Points for PyInstaller
[project.entry-points.pyinstaller40]
hook-dirs = "mpo_yampfs.__pyinstaller:get_hook_dirs"


[tool.setuptools]
packages = ["mpo_yampfs", "mpo_yampfs.__pyinstaller"]

[tool.setuptools.package-data]
"*" = ["yampfs/**"]
"yampfs_py.yampfs" = ["**"]


[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "mpo_yampfs_tests",
]